apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: agentic-demo

resources:
  - ../agents/templates
  - ../ui/templates

patches:
  - target:
      kind: Secret
      name: agentic-app-be-secret
    path: secret-patch.yaml
  - target:
      kind: ClusterRoleBinding
      name: oauth-proxy-agentic-sa
    path: patch-crb.yaml